tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
cask "osxfuse"
brew "bat"
brew "ffmpeg"
brew "firebase-cli"
brew "mas"
brew "pandoc"
brew "poppler"
brew "ruby"
brew "sshfs"
brew "tree"
brew "youtube-dl"
cask "1password"
cask "alt-tab"
cask "calibre"
cask "discord"
cask "docker"
cask "dropbox"
cask "font-inconsolata-for-powerline"
cask "font-source-han-sans"
cask "google-chrome"
cask "inkscape"
cask "iterm2"
cask "karabiner-elements"
cask "rectangle"
cask "visual-studio-code"
cask "zoomus"
mas "Kindle", id: 405399194
mas "LINE", id: 539883307
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft To Do", id: 1274495053
mas "Microsoft Word", id: 462054704
mas "OneDrive", id: 823766827
mas "Slack", id: 803453959
