source "$ZDOTDIR"/inits/00-zsh.zsh
source "$ZDOTDIR"/inits/01-zim.zsh
source "$ZDOTDIR"/inits/10-alias.zsh
source "$ZDOTDIR"/inits/20-builtin.zsh
source "$ZDOTDIR"/inits/21-builtin-dotenv.zsh
source "$ZDOTDIR"/inits/22-builtin-firebase.zsh
source "$ZDOTDIR"/inits/23-builtin-git.zsh
source "$ZDOTDIR"/inits/24-builtin-progress.zsh
source "$ZDOTDIR"/inits/30-hook-clean.zsh
source "$ZDOTDIR"/inits/31-hook-magic-enter.zsh
source "$ZDOTDIR"/inits/40-theme.zsh
